jobs:
  include:
  - stage: Build

    sudo: required
    services:
    - docker
    script: docker build -t vibioh/`make name`:`make version` .
    after_success: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin && \
      docker push vibioh/mjml-api:`make version`

  - stage: Publish

    sudo: required
    services:
    - docker
    script: |
      echo ${DOCKER_PASS} | docker login -u vibioh --password-stdin
      docker pull vibioh/mjml-api:`make version`
      docker tag vibioh/mjml-api:`make version` vibioh/mjml-api:latest
      docker push vibioh/mjml-api:latest

  - stage: Deploy

    script: |
      sed \
        -e "s|\${HTTP_PASSWORD}|${HTTP_PASSWORD}|g" \
        -e "s|\${ROLLBAR_TOKEN}|${ROLLBAR_TOKEN}|g" \
        docker-compose.yml > docker-compose-env.yml
    deploy:
    - provider: script
      skip_cleanup: true
      script: 'curl -H "Authorization: GitHub ${GITHUB_OAUTH_TOKEN}" -X POST "https://dashboard-api.vibioh.fr/deploy/mjml/?rollbar_token=${ROLLBAR_TOKEN}&user=`make author`&revision=`make version`&environment=prod" --data-binary @docker-compose-env.yml'

stages:
  - Build
  - name: Publish
    if: branch = master
  - name: Deploy
    if: branch = master

notifications:
  email: false
