apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mjml
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: '0.0.46'
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: flux-system
      interval: 120m
  values:
    nameOverride: mjml
    podAnnotations:
    image:
      repository: vibioh/mjml:202102211151 # {"$imagepolicy": "default:mjml-api"}
    port: 3000
    prometheus:
      port: 3000
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
