apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mjml
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.49"
      sourceRef:
        kind: HelmRepository
        name: vibioh
        namespace: default
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: mjml
    podAnnotations:
    image:
      name: vibioh/mjml
      tag: "202103070909" # {"$imagepolicy": "default:flux-mjml-api:tag"}
    port: 3000
    prometheus:
      port: 3000
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
